# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d34d77abdda83048a63365482790836267d25df249750ddf6e4db4533992d4a188122a26d518bb8dbf29b7338bf43e7b2154c374a169165c80c1bc750493415

test:
  secret_key_base: 4129c30a580b339241ab7d00dc31942fedbf6672ed0ef0d4f296f438f6f67e109b5ef13326e360816e2cfc41cb59dcabdd824fb286db5f287dc046216d789c3c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
